---
- name: install system packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - build-essential 
  - python-dev 
  - python-pip 
  - bridge-utils 
  - ntp 
  - zip 
  - unzip 
  - curl
  - git
  - jq
  tags:
    - common

- name: install latest awscli boto docker_py
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
  - awscli
  - boto
  - docker_py
  tags:
    - common
